### ISSUE TITLE
Configuration based SAP CAL SAP NetWeaver 7.50 SP1 AS ABAP and SAP BW on SAP HANA SPS10 - Developer Edition

### ISSUE THREAD

**Issue by ROBROICH** [azuredevcollege/SAP#16]
In order to make the steps more and easier reproducible a suggestion would be to implement the tutorial based on the following SAP CAL image:
SAP NetWeaver 7.50 SP1 AS ABAP and SAP BW on SAP HANA SPS10 - Developer Edition
https://caldocs.hana.ondemand.com/caldocs/help/Getting%20started%20guide%20NetWeaver%207.5%20on%20SAP%20HANA_v2.pdf

**Comment by alschroe** [comment]
We are happy if you can contribute this!
