### ISSUE TITLE
Netweaver SAML config: Are all reply URLs mandatory?

### ISSUE THREAD

**Issue by ROBROICH** [azuredevcollege/SAP#19]
Are all reply URLs in this screenshot mandatory?
https://github.com/azuredevcollege/SAP/blob/master/sap-oauth-saml-flow/AzureActiveDirectoryConfiguration/img/AADEnterpriseApplicationRegistrationSAPSingleSignOnBasicConfiguration.png

**Comment by alschroe** [comment]
To be reviewed in Iteration 3

**Comment by alschroe** [comment]
Not all reply URLs were mandatory - the documentation should now reflect this.
