### ISSUE TITLE
Include Microsoft & SAP references / links?

### ISSUE THREAD

**Issue by ROBROICH** [azuredevcollege/SAP#20]
Include SAP & Microsoft references / links?
https://wiki.scn.sap.com/wiki/display/Security/Using+OAuth+2.0+from+a+Web+Application+with+SAML+Bearer+Assertion+Flow

https://docs.microsoft.com/en-us/azure/active-directory/saas-apps/sap-netweaver-tutorial --> Explain the difference between NW system config for SAML & OAuth (Enterprise apps needed for SSO with SAML and OAUTH flow --> Potential for wrong config)

https://blogs.sap.com/2020/07/17/principal-propagation-in-a-multi-cloud-solution-between-microsoft-azure-and-sap-cloud-platform-scp/

**Comment by alschroe** [comment]
Integrated changes
