### ISSUE TITLE
Trusted IdP configuration in SAP? 

### ISSUE THREAD

**Issue by ROBROICH** [azuredevcollege/SAP#22]
Configuration of IdP in SAP via config file and certificate of Azure AD not required?
https://docs.microsoft.com/en-us/azure/active-directory/saas-apps/sap-netweaver-tutorial#configure-sap-netweaver-using-saml

--> See trusted IdP config:
https://docs.microsoft.com/en-us/azure/active-directory/saas-apps/sap-netweaver-tutorial#register-the-new-oauth-20-client-id-with-the-creation-wizard

**Comment by alschroe** [comment]
Is now included, thanks
