### ISSUE TITLE
Chapter / Section "How to debug/troubleshoot?" 

### ISSUE THREAD

**Issue by ROBROICH** [azuredevcollege/SAP#23]
Include a section "How to debug/troubleshoot?" with tools like:
 SEC_TRACE_ANALYZER
https://<sapurl>/sap/bc/webdynpro/sap/sec_diag_tool?sap-client=122&sap-language=EN#

1688545 - OAuth 2.0 Server in AS ABAP Troubleshooting

**Comment by ROBROICH** [comment]
Potential error source is the missing ICF handler for OData.
![image](https://user-images.githubusercontent.com/51105958/90260365-b0e60700-de4b-11ea-9d4e-7042add97b88.png)

**Comment by alschroe** [comment]
We are happy if you could contribute this!
